# Generated by Django 4.1.4 on 2022-12-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='structured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
